### ISSUE TITLE
[BE] 회원가입 기능 구현하기

### ISSUE THREAD

**Issue by koreandroid** [kosta-donana/luce-vita-server#1]
- [x] 모델 생성 (기존 유저인지 확인을 위한 DB 연결)
- [x] 미인증 유저 확인 (미인증 경우, auth.user 테이블에서 해당 데이터 삭제 후 재인증 요청)
- [x] 인증 요청 서비스 생성
- [x] 라우터 생성
- [x] 쿠키 설정
- [x] develop 브랜치 merge하기

**Comment by hhejo** [comment]
화이팅

**Comment by Claire-Nam** [comment]
테스트 코드 작동 확인
